# LOOCV-Prediction Without Prediction Error Estimates
```{r message = FALSE, echo = FALSE}
if (!require("pacman")) install.packages("pacman")
pacman::p_load("data.table", "ggplot2", "ggthemes", "dplyr", "forcats", 
               "viridis", "tidyr", "modelr")

knitr::knit_hooks$set(inline = function(x) {
  prettyNum(x, big.mark = ",", digits = 2)
})
knitr::opts_knit$set(root.dir = "~/gamazon/",
                     inline = TRUE,
                     verbose = FALSE)
knitr::opts_chunk$set(fig.width = 8, fig.height = 6,
                      warning = FALSE, echo = FALSE)
```

```{r Load-LOOCV-Data, cache = TRUE}
# Load log files and data
run_log <- fread("./data/derived/na_fraction_pred_log.txt")

# LOOCV 
loocv_nms <- run_log[CV == "LOOCV", Job_ID, ]
loocv <- lapply(seq_along(loocv_nms), FUN = function(i) {
  readRDS(paste0("./data/derived/predictions/", loocv_nms[i], ".RDS"))
})
loocv <- rbindlist(loocv)
```


```{r Rename-Traits, cache = TRUE}
loocv_clean <- loocv %>%
  mutate(Trait = fct_recode(Trait, 
                            "FAT" = "FETT",
                            "PRO" = "RPR",
                            "DMY" = "GTM",
                            "DMC" = "GTS",
                            "SUG" = "XZ"),
         Trait = fct_relevel(Trait, c("DMY", "DMC", "ADF", "FAT", "PRO", "STA",
                                      "SUG")),
         Dent_NA_Fraction = as.factor(as.character(Dent_NA_Fraction)),
         Flint_NA_Fraction = as.factor(as.character(Flint_NA_Fraction)),
         Residuals = y - yhat,
         Predictor = fct_recode(Predictor,
                                "mRNA" = "mrna",
                                "SNP" = "snp")
  )
```


## Reduced Data
### Predicted vs. residuals
```{r Complete-Data-Residuals, cache = TRUE, dependson = "Rename-Traits"}
full_pred_resid <- loocv_clean %>%
  filter(Dent_NA_Fraction == 0, Flint_NA_Fraction == 0) %>%
  group_by(Predictor) %>%
  do(plot = ggplot(., aes(x = yhat, y = Residuals)) +
       geom_point(size = 0.5) +
       geom_ref_line(h = 0) +
       facet_wrap(~ Trait, nrow = 2, scales = "free") +
       theme(axis.text.x = element_text(angle = 60, hjust = 1, vjust = 1)) +
       xlab("Predicted") +
       ylab("Residuals") +
       ggtitle(.$Predictor))
invisible(lapply(full_pred_resid$plot, FUN = print))
```

### Predicted vs. Observed
```{r Complete-Data-y-yHat, cache = TRUE, dependson = "Rename-Traits"}
full_y_yhat <- loocv_clean %>%
  filter(Dent_NA_Fraction == 0, Flint_NA_Fraction == 0) %>%
  group_by(Predictor) %>%
  do(plot = ggplot(., aes(x = y, y = yhat)) +
       geom_point(size = 0.5) +
       geom_abline(slope = 1, linetype = "dashed", color = "blue") +
       facet_wrap(~ Trait, nrow = 2, scales = "free") +
       theme(axis.text.x = element_text(angle = 60, hjust = 1, vjust = 1)) +
       xlab("Observed") +
       ylab("Predicted") +
       ggtitle(.$Predictor))
invisible(lapply(full_y_yhat$plot, FUN = print))
```


## Predictive Ability for 'Full' vs 'Reduced' Data
```{r Non-Imputed-Pred-Ability, cache = TRUE}
loocv_tbl_cap <- paste("Predictive abilities for the 'reduced' set of hybrids",
                       "using two different predictors and seven agronomic",
                       "traits. Results are ranked by predictive ability.")
pred_reduced <- loocv_clean %>%
  filter(Dent_NA_Fraction == 0, Flint_NA_Fraction == 0) %>%
  mutate(Predictor = as.factor(Predictor)) %>%
  droplevels() %>%
  group_by(Predictor, Trait) %>%
  summarize(Pred_Ability = round(cor(y, yhat), digits = 2)) %>%
  spread(key = "Predictor", value = "Pred_Ability") %>%
  rename(Reduced_mRNA = mRNA,
         Reduced_SNP = SNP)
```


```{r Imputed-Pred-Ability, cache = TRUE}
run_log <- fread("./data/processed/prediction_log/log_list.txt")

# LOOCV 
full_loocv_nms <- run_log[CV == "LOOCV", Job_ID, ]
full_loocv <- lapply(seq_along(full_loocv_nms), FUN = function(i) {
  readRDS(paste0("./data/processed/predictions/", full_loocv_nms[i], ".RDS"))
})
full_loocv <- rbindlist(full_loocv)

full_loocv_clean <- full_loocv %>%
  mutate(Trait = as.factor(Trait),
         Trait = fct_recode(Trait, 
                            "FAT" = "FETT",
                            "PRO" = "RPR",
                            "DMY" = "GTM",
                            "DMC" = "GTS",
                            "SUG" = "XZ"),
         Trait = fct_relevel(Trait, c("DMY", "DMC", "ADF", "FAT", "PRO", "STA",
                                      "SUG")),
         Residuals = y - yhat,
         Predictor = as.factor(as.character(Imputation)),
         Predictor = fct_recode(Predictor,
                                "mRNA" = "TRUE",
                                "SNP" = "FALSE")
  )
full_loocv_tbl_cap <- paste(
  "Predictive abilities for the 'full' and the 'reduced' set of hybrids using",
  "two different predictors and seven agronomic traits."
  )
full_loocv_clean %>%
  droplevels() %>%
  group_by(Predictor, Trait) %>%
  summarize(Pred_Ability = round(cor(y, yhat), digits = 2)) %>%
  spread(key = "Predictor", value = "Pred_Ability") %>%
  rename(Full_mRNA = mRNA,
         Full_SNP = SNP) %>%
  full_join(y = pred_reduced, by = "Trait") %>%
  knitr::kable(caption = full_loocv_tbl_cap, booktabs = TRUE)
```
