---
title: "Fernando LOOCV"
author: "Matthias Westhues"
date: "`r Sys.Date()`"
output: pdf_document
---

Meine Annahme ist, dass die effiziente Implementierung von LOOCV (Cheng et al.,
2016) den gesamten Stichprobenumfang (mit Ausnahme der einen Hybride im test 
set) als training set nutzt.
Allerdings wollen wir LOOCV ja nur auf T0-Hybride anwenden.
In diesem Fall kann nicht jede Hybride, die zuvor Teil des training sets fuer 
die Vorhersage einer anderen Hybride war, vom training in das test set 
ueberfuehrt werden.
Ich habe das nachfolgend mal anhand eines kleinen Beispiels illustriert:

|:---:|:----:|
|ID   |Hybride|
|1    |Aa     |
|2    |Ab     |
|3    |Ac     |
|4    |Ba     |
|5    |Bb     |
|6    |Bc     |
|7    |Ca     |
|8    |Cb     |
|9    |Cc     |

: Hybride und ihre korrespondierenden IDs.

|:--------:|:------------:|
| Test Set | Training Set |
| 1        | 5, 6, 8, 9   |        
| 2        | 4, 6, 8, 9   |        
| 3        | 4, 5, 7, 8   |        
| 4        | 2, 3, 8, 9   |        
| 5        | 1, 3, 7, 9   |        
| 6        | 1, 2, 7, 8   |        
| 7        | 2, 3, 5, 6   |        
| 8        | 1, 3, 4, 6   |        
| 9        | 1, 2, 4, 5   |        

: Hybride im test set und korrespondierende T0-Hybride im training set. Die Hybride sind mit ihren IDs aus der vorherigen Tabelle gekennzeichnet. 

Hybride \#1 kann mit den Hybriden 5, 6, 8 und 9 vorhergesagt werden, aber die
Hybride \#5 kann nicht mit den Hybriden 6 und 8 vorhergesagt werden, Hybride 
\#6 kann nicht mit den Hybriden 5, 6 und 9 vorhergesagt werden, Hybride \#8 
kann nicht mit den Hybriden 5 und 9 vorhergesagt werden, und Hybride \#9 kann 
nicht mit den Hybriden 6 und 8 vorhergesagt werden.