---
title: "Hybrid Prediction with Extreme Gradient Boosting"
author: Matthias Westhues
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_notebook:
    number_sections: true
    toc: true
    fig_width: 7
    fig_height: 4.5
    theme: readable
    highlight: tango
---

```{r setup}
if (!require("pacman")) install.packages("pacman")
# Load 'xgboost' before 'dplyr' because the former relies on 'plyr' functions,
# which cause conflicts with 'dplyr' functions when not not loaded first.
pacman::p_load("xgboost")
pacman::p_load_gh("tidyverse/dplyr")
pacman::p_load(
  "purrr", "readr", "stringr", "ggplot2", "tibble", "forcats", "tidyr", 
  "assertr", "knitr", "rprojroot", "caret", "DMwR", "propagate"
)
knit_hooks$set(inline = function(x) {
  prettyNum(x, big.mark = ",", digits = 2)
})
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(fig.width = 8, fig.height = 6,
                      warning = FALSE, echo = FALSE)
```



```{r Load_Data}
# Response variable.
pheno <- "./data/derived/maizego/tst_pheno_tibble.RDS" %>% 
  readRDS() %>% 
  filter(Trait == "Silkingtime")

# Predictor variables
mrna <- "./data/derived/maizego/mrna.RDS" %>% 
  readRDS()

# Extract genotypes for which predictor data (i.e. mRNA information) are
# available.
genotypes <- mrna %>% 
  rownames()
```


```{r Data_Inspection}
transform_boxcox <- function(x) {
  x %>% 
    BoxCoxTrans() %>% 
    predict(., x)
}

pheno %>% 
  rename(
    y = Value
  ) %>% 
  mutate(
    box_cox_y = transform_boxcox(y)
  ) %>% 
  gather(key = Preprocessing, value = Value, -Genotype, -Trait) %>% 
  ggplot(aes(x = Value)) +
  geom_histogram(bins = 80) +
  facet_wrap(~ Preprocessing, scales = "free")
```

In the case of the trait "days to silking" pre-processing of the response 
variable seems to be pointless so we will just stick with the original values, 
which are approximately normally distributed.




```{r}
# mRNA correlations
mrna_corr <- mrna %>% 
  bigcor(fun = "cor", verbose = FALSE) %>% 
  .[1:nrow(.), 1:ncol(.)]
```



```{r Prediction}
train_control <- trainControl(
  method = "repeatedcv",
  number = 10,
  repeats = 5
)

xgb_grid <- expand.grid(
  nrounds = 1e3,
  eta = 0.01,
  max_depth = c(2L, 10L),
  gamma = c(0, 10),
  colsample_bytree = c(0.1, 0.4),
  min_child_weight = c(1L, 10L),
  subsample = c(0.5, 1)
)

# Extract the agronomic BLUEs, ordered according to the mRNA matrix..
response <- pheno %>% 
  dplyr::slice(., match(Genotype, genotypes)) %>% 
  select(Value) %>% 
  flatten_dbl()

set.seed(340934)
xgb_res <- train(
  x = mrna,
  y = response,
  method = "xgbTree",
  tuneGrid = xgb_grid,
  trControl = train_control,
  trace = FALSE
)

yhat <- predict(xgb_res, newdata = mrna)
plot(response, yhat)

set.seed(340934)
train_idx <- seq_len(80)
xgb_fit <- train(
  x = mrna[train_idx, ],
  y = response[train_idx],
  method = "xgbTree",
  tuneGrid = data.frame(
    nrounds = 1000,
    max_depth = 10,
    eta = 0.01,
    gamma = 10,
    colsample_bytree = 0.1,
    min_child_weight = 1,
    subsample = 1   
  ),
  trControl = train_control,
  verbose = FALSE
)


cor(response[-train_idx], predict(xgb_fit, newdata = mrna[-train_idx, ]))
```